version: '3'
services:

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vaguada
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: santino
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  springboot:
    container_name: springboot
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
