version: '3'
services:

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vaguada
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_USER: santino
      MYSQL_PASSWORD: 1234
    command: --bind-address=0.0.0.0

    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  springboot:
    container_name: springboot
    build: ./api
    ports:
      - "80:80"
    depends_on:
      - mysql
